# -*- coding: utf-8 -*-
"""karthikakpillai

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UV7LF0lwCYpZ24cpEJrAjKJ_RI48XYpD

Importing Libraries
"""
pip install matplotlib
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

"""Uploading Dataset

"""

from google.colab import files
uploaded = files.upload()

df = pd.read_csv('job_salary_prediction_dataset.csv')
df.head()

df.shape

"""Basic Information

"""

print(df.info())
print(df.describe())

"""Classification (creating target variable)"""

df['salary_class'] = pd.qcut(df['salary'], q=3, labels=['Low','Medium','High'])
df.drop('salary', axis=1, inplace=True)

"""EDA"""

plt.figure()
sns.countplot(x='salary_class', data=df)
plt.title('Salary Class Distribution')
plt.show

"""Handling categorical variables"""

le = LabelEncoder()

for col in df.select_dtypes(include='object').columns:
    df[col] = le.fit_transform(df[col])

"""Feature Engineering"""

x=df.drop('salary_class', axis=1)
y=df['salary_class']

"""Training test data and split"""

x_train, x_test, y_train, y_test=train_test_split(x,y, test_size=0.2, random_state=42)

"""Scaling"""

scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

"""Model Building"""

models={
    "Logistic Regression": LogisticRegression(),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier()
}
result={}
for name, model in models.items():
  model.fit(x_train, y_train)
  y_pred=model.predict(x_test)
  acc=accuracy_score(y_test, y_pred)
  result[name]=acc
  print(f"{name} Accuracy: {acc}")

"""Model Comparison"""

plt.figure()
sns.barplot(x=list(result.keys()), y=list(result.values()))
plt.title('Model Comparison')
plt.xticks(rotation=30)
plt.show()

"""Hyperparameter tuning (random forest)"""

param_grid={
    'n_estimators': [50,100],
    'max_depth': [None, 10, 20]
}
grid=GridSearchCV(RandomForestClassifier(), param_grid, cv=3)
grid.fit(x_train, y_train)
best_model=grid.best_estimator_

"""Final Evaluation"""

y_pred=best_model.predict(x_test)  #model makes prediction
print("Final Model Accuracy:", accuracy_score(y_test, y_pred)) #accuracy tested #recall checks if model misses important cases
print(classification_report(y_test, y_pred)) #f1 score gives the balanced evaluation



"""Confusion Matrix"""

cm=confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt='d')
plt.title('Confusion Matrix')
plt.show()

import pickle
pickle.dump(best_model, open('model.pkl', 'wb'))
